#ifndef CUSTOMMENUTOOLBAR_H
#define CUSTOMMENUTOOLBAR_H
#include <QMainWindow>
#include <QMenuBar>
#include <QToolBar>
#include <QAction>

class CustomMenuToolbar
{
public:
    CustomMenuToolbar(QMainWindow *mainWindow);
    void createMenus();
    void createToolbars();
private:
    QMainWindow *mainWindow;
    QMenu *fileMenu, *editMenu, *alignMenu, *distributeMenu, *viewMenu, *unitsMenu, *runMenu, *operatingModes;
    QMenu *databaseMenu, *reportsMenu, *windowMenu, *helpMenu;
    QAction *newAction;
    QAction *saveAction;
    QAction *saveAsAction;
    QAction *openAction;
    QAction *openControlPanelAction;
    QAction *manageUserAction;
    QAction *printAction;
    QAction *printAllAction;
    QAction *exportAction;
    QAction *pageToPdf;
    QAction *pageWithResultToPDF;
    QAction *pageToEPS;
    QAction *pageWithResultToEPS;
    QAction *pageToJPEG;
    QAction *pageToTIFFColor;
    QAction *pageToTIFFBW;
    QAction *plantToPdf;
    QAction *plantWithResultToPDF;
    QAction *plantToEPS;
    QAction *plantWithResultToEPS;
    QAction *setTitlePrint;
    QAction *setUserPreference;
    QAction *closeAction;
    QAction *loadAction;
    QAction *clearAction;
    QAction *undoAction;
    QAction *redoAction;
    QAction *copyAction;
    QAction *cutAction;
    QAction *pasteAction;
    QAction *deleteAction;
    QAction *selectAllAction;
    QAction *topAction;
    QAction *bottomAction;
    QAction *leftAction;
    QAction *rightAction;
    QAction *verticalByCenter;
    QAction *horizontalByCenter;
    QAction *refreshAction;
    QAction *zoomInAction;
    QAction *zoomToNormalAction;
    QAction *zoomOutAction;
    QAction *zoomToFitAction;
    QAction *drawOrthogonalAction;
    QAction *metricAction;
    QAction *imperialAction;
    QAction *displayWaterAction;
    QAction *displayToolbarAction;
    QAction *displayToolTipsAction;
    QAction *runAction;
    QAction *runStage;
    QAction *runPlant;
    QAction *runSave;
    QAction *turnOffAllRedFlags;
    QAction *openConfigurationAdvisor;
    QAction *addNewOperatingMode;
    QAction *manageOperatingMode;
    QAction *ModeReport;
    QAction *ModeDifferencesReport;
    QAction *deleteAllOperatingMode;
    QAction *whatAreOperatingModes;
    QAction *viewAllCrushers;
    QAction *viewEditSpecifications;
    QAction *viewEditEmissionTables;
    QAction *viewScreenSizeConversionTable;
    QAction *importDataFromPreviousVersion;
    QAction *manageAttachments;
    QAction *createReportForSelectedItems;
    QAction *createReportForAllItemsOnWorksheet;
    QAction *createEmissionReportForSelectedItems;
    QAction *createEmissionReportForAllItemsOnWorksheet;
    QAction *setTitleAndPrintOptions;
    QAction *refreshAll;
    QAction *collapseAll;
    QAction *restoreAll;
    QAction *openHelpSystem;
    QAction *getAggFlowUpdates;
    QAction *requstSupport;
    QAction *sendSuggestion;
    QAction *aggFlowDisclaimer;
    QAction *aggFlowLicense;
    QAction *about;
};

#endif // CUSTOMMENUTOOLBAR_H
